### ISSUE TITLE
How can I use pushList with an optional sequence of sequence?

### ISSUE THREAD

**Issue by phuongtran7** [Svalorzen/asn1cpp#2]
Hi,

I'm trying out the asn1cpp for my project and everything seems to be working fine. However, I'm having problem with creating an optional sequence. The schema is something like this:
```
Message ::= SEQUENCE
{
       header MessageHeader,
       content MessageContent,
       content-seqOf SEQUENCE SIZE (1..4) OF MessageContent OPTIONAL
}
```

I can create the `header` and the main `content` sequence using `asn1cpp::makeSeq` just fine. However, when I tried to create another `MessageContent` to push it into the `content-seqOf`, the `pushList` macro always return false.

```cpp
auto encode_message = asn1cpp::makeSeq(Message);
auto sub_content= asn1cpp::makeSeq(MessageContent);
auto result = asn1cpp::sequenceof::pushList(*encode_message->content-seqOf, sub_content);
```

I tried both `setOf` and `sequenceOf` but none succeeded.

Thank you so much for your time and help.

**Comment by Svalorzen** [comment]
Hey, unfortunately it has been around three years since I have been working on this project, so my memory is not super-fresh on the details.

Looking in it seems that there are no tests with an optional sequence, so it might be that the current code does not support that (there's also no code with a specified size, so that's another possibility).

If removing both of those things makes it work again, it's possible that the code needs to be modified to account for the optional. The main problem, if I remember correctly, is that asn1 generates a bunch of functions to interact with the data, and if you use the wrong one things might not work.

The code that gets run for `pushList` is the same for both `sequenceof` and `setof`:

```
        template <typename T, typename V>
        bool adderElement(T & field, const V & value) {
            typename Impl::ArrayType<T>::type * ptr = nullptr;
            if (!asn1cpp::setterField(ptr, value))
                return false;
            return asn_set_add(&field, ptr) == 0;
        }
```

This code is in `SetOf.hpp`. You could try to put a print in there and see which one of the two calls fails, and where, so you know which asn1 call is failing.

Please do write what you find here. Ideally if it's something the library is missing in the end we could add a new test-case and the code to make it work.

**Comment by phuongtran7** [comment]
Hi,

Thank you so much for your prompt reply. I really appreciate it. Unfortunately, my understanding for both `asn1cpp` and `asn1c` in general is rather limited. I will try and add any information I can gather.

First of all, just like you mentioned both `setof` and `sequenceof` invoked the `adderElement` method in the `SetOf.hpp`.

I followed the debugger and it seems that everything works fine until the call to:

````asn_set_add(&field, ptr)````

I think because `encode_message->content-seqOf` is a nullptr when I call the `pushList`, due to the fact that it is optional. So when the `asn_set_add` is called, the `field` still is a nullptr and it failed at the check:

```
if(as == 0 || ptr == 0) {
	errno = EINVAL;		/* Invalid arguments */
	return -1;
}
```

**Comment by phuongtran7** [comment]
I'm so sorry for the multiple responses in a row, but after messing around with it a little more, I discovered that if I allocated the space before call `pushList` it will work:

```cpp
auto encode_message = asn1cpp::makeSeq(Message);
auto sub_content= asn1cpp::makeSeq(MessageContent);

// Allocate the sequence before adding new sequence to it
encode_message->content-seqOf =
        (Message__content_seqOf*)calloc(1,sizeof(Message__content_seqOf ));

// Then this will work
auto result = asn1cpp::sequenceof::pushList(*encode_message->content-seqOf, sub_content);
```

I can try adding this inside the `adderElement` call but as I mentioned, I'm not familiar with `asn1cpp` so I don't know how long it will take me or I can even do this.

**Comment by Svalorzen** [comment]
So I'm trying to replicate your problem here, and I added an optional sequence to the tests, and my code did not compile. Then I realized in the code you posted, you are dereferencing in `pushList`: `pushList(*encode_message->content-seqOf, ...)`. You probably did this to make the code compile, but what this basically means is that yeah, this is currently not supported.

You can't just dereference the `content-seqOf` pointer to make it compile, since when you first push a new element to the list you would first need to allocate the memory for the list. If you simply dereference the pointer, it's undefined behavior.

I'll see if I can do something about it; it's always a bit tricky to handle memory with asn1 (which is why this lib exists in the first place). If I can't manage I'd suggest you try to remove the optional; in the end an empty list is empty, and you could try to add a separate boolean variable to indicate whether the list should be read or not.

**Comment by phuongtran7** [comment]
Hi,

Thank you so much for the clear explanation. I finally understand it a little bit more.

Unfortunately, the schema isn't mine so I cannot easily modify it. I'll have to try and be more careful around these optional fields as the schema I'm working with has a ton of them.

Again, thank you so much for your time and help.

**Comment by Svalorzen** [comment]
Hey, I think I might have fixed the problem. Give me a minute to push the changes.

**Comment by Svalorzen** [comment]
Alright, I have pushed. Please remove the dereferencing operator from the `pushList` call, and let me know if it works :)

**Comment by phuongtran7** [comment]
Wow, that was extremely fast. Thank you so much for doing it.

I just did a quick test with my schema and it works extremely well. It also fixed one of other questions that I intent to ask you later too.

Now the `asn1cpp::sequenceof::getSize` also work without having to dereference beforehand on an optional sequence too.

While, we are on this, it seems that I still need to dereference the optional sequence, after check whether it's a nullptr, to get the view. Is this the correct way to do this:

```
if (encode_message->content_seqOf)
{
	auto size = asn1cpp::sequenceof::getSize(encode_message->content_seqOf);

	for (auto i = 0; i < size;i++) {
		// Still need to dereference here
		auto sub_content_view = asn1cpp::sequenceof::getView(*encode_message->content_seqOf, MessageContent , i);
	}
}
```

**Comment by Svalorzen** [comment]
Yeah, my bad, I just forgot to add it. Unfortunately I don't remember how this library works so well xD

Let me add support for that as well, shouldn't take too long.

**Comment by Svalorzen** [comment]
Done. Please keep in mind that you should never need to:

1 - Manually allocate memory
2 - Manually dereference pointers

If one of these two things happens, then the library does not support it. This means that you can do it, but you should be very sure of what you are doing.

I've also fixed a memory leak I had left in for the clears. Please be sure to test your applications with valgrind or an equivalent tool for memory leaks. Hopefully everything works well, but you never know :)

**Comment by phuongtran7** [comment]
Hi again,

Thank you so much for the new update. I just tested it and it's working perfectly. I will keep these rules in mind.

Also, I've actually never used valgrind or something similar before, now it would be a great excuse to try and learn it. And I think with that this issue can be closed now. Do you want me to close it?

 Thank you so much for your time and help. I really appreciate it.

**Comment by Svalorzen** [comment]
Hey, feel free to close the issue. Glad to be of help!
